### ISSUE TITLE
Forum et URL propres

### ISSUE THREAD

**Issue by Balzac40** [soosyze/soosyze#138]
Bonjour et bravo pour ce projet très prometteur !

**Deux soucis :**
- impossible d'utiliser le forum : après inscription directe (aucun succès avec les différentes applications dont GitHUb), pas de réception du mail de confirmation, puis ensuite impossible de redemander l'envoi du mail de vérification)
- sous XAMPP, l'option rendre les URL propres ne fonctionne pas (le site n'est plus opérationnel) : que faut-il faire ?

Merci !

**Comment by noelma** [comment]
Bonjour @Balzac40 et merci de votre retour,

Pour commencer, vous êtes le premier à écrire une Issue sur Github donc félicitation ^^.

Concernant votre problème de réécriture dURLs je vais publier un bout de documentation d’ici 14h sur le site, je vous ferais parvenir le lien dans cette Issue.

Pour le forum je n'avais pas rencontré ce problème jusqu'à présent, ça risque de prendre plus de temps à corriger. Il faudra malheureusement attendre ce week-end pour avoir une correction convenable.

Si vous rencontrez d'autres problèmes ou bugs d'ici là, n'hésitez pas a nous contacter avec les issues Github, sur notre Discord ou sur Mastodon. Je tacherais de vous répondre.

Cordialement ;)

**Comment by noelma** [comment]
Voici le lien de la documentation concernant la réécriture d'URLs avec Soosyze : 

https://soosyze.com/documentation/faq/comment-rendre-urls-soosyze-propres

**Comment by Balzac40** [comment]
@noelma Merci ! Pour un fonctionnement sous Windows 10 + XAMPP, il convient d'utiliser un VirtualHost, et ça fonctionne sans problème.

**Comment by noelma** [comment]
De riens, j'aurais dû commencer à écrire cette FAQ depuis longtemps, ça m'a permis d'y ajouter la première question à la rubrique utilisateur ^^.

Sinon concernant le Forum j'ai regardé ça entre midi et 2, le problème est moins gros que prévus, juste un problème au niveau du serveur SMTP et les liens OAuth non configurés.

Tu peux à nouveau recevoir des mails ou te connecter avec ton compte Github ou Discorde ;)
