### ISSUE TITLE
Création d'item dans les menus

### ISSUE THREAD

**Issue by jackplux** [soosyze/soosyze#183]
Bonjour, :-)

Il semble qu'en créant les items dans les menus, bien que la case soit cochée, les liens ne s'ouvent pas dans une autre fenêtre.

**Comment by noelma** [comment]
Le bug a été reproduit en local et est en cours de résolution.
Merci de l'avoir signalé :)

**Comment by jackplux** [comment]
Quelle joie ! ;)
