### ISSUE TITLE
XSS in content editing page

### ISSUE THREAD

**Issue by Jindom** [soosyze/soosyze#184]
Hi Team,
There is a XSS in soosyze CMS content editing function.
The problem exist because the function ```edit``` in soosyze/core/module/node/controller/node.php did not filter out some malicious string like ```alert(...)``` which may cause a stored XSS. Please see the following screenshot for reference:

![image](https://user-images.githubusercontent.com/26808448/93666346-1616c300-fab0-11ea-9fe7-80c8a44d42f1.png)

![image](https://user-images.githubusercontent.com/26808448/93666354-2fb80a80-fab0-11ea-8444-e1fe4e33644e.png)

![image](https://user-images.githubusercontent.com/26808448/93666358-36468200-fab0-11ea-9b9f-9de3dadba66d.png)

Also the CMS did not add Secure and HTTPOnly flag for the cookie session which made this kind of cookie stealing attack possible.

**Comment by noelma** [comment]
Hello,

XSS attack problems are known within the Soosyze CMS.

During the development of the beta2 version, we developed the [KSES ](https://github.com/soosyze/kses) component to filter the strings entered by the user.

It will be implemented before the stable version of Soosyze.
