### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [soosyze/soosyze#256]
Hey there!

I belong to an open source security research community, and a member (@bugruto) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by JamieSlome** [comment]
@noelma - is this repository still maintained?

Just for reference, the report can be found here:

https://www.huntr.dev/bounties/da3a62e7-378c-4dd3-95ca-24854999c337/

It is private and only accessible to maintainers with repository write permissions! 👍

**Comment by noelma** [comment]
@JamieSlome Yes the project is still maintained and active, I have taken your feedback into account. I will add security instructions for version 2 which is under development.

**Comment by JamieSlome** [comment]
@noelma - thanks! 👍

**Comment by JamieSlome** [comment]
@noelma - just for your reference, both reports can be found here:

https://huntr.dev/bounties/da3a62e7-378c-4dd3-95ca-24854999c337/
https://huntr.dev/bounties/5596537f-cec6-4e1e-88b4-8451e1e610b2/

They are currently private and only accessible to maintainers with repository write permissions 👍
